---
title: "Tutorial 1: R Basics"
author: "Amrom"
output: html_document
---

***
The best way to learn R is by doing it. But beo In this tutorial we will learn the basics of working with R. 

### Basic R Commands
In excel you put your data in a spreadsheet if you're working with a big table of data, and if you're just working with simple calculations, you just work with the individual cells. In R it works a bit different, the data goes into a variable. R recognizes whether you're working with a big table of data and converts that variable into a 'dataframe' or if you're just putting a number or some text in where it'll convert the variable into a 'numeric' or 'character'. 

To assign values to variables, use `<-`, the assignment operator. You can also use  `=`. I like the arrow better. 

To get some practice doing this stuff with a web program that looks a lot like the Rstudio you have on your computer. Go to this [datacamp website ](https://campus.datacamp.com/courses/free-introduction-to-r/chapter-1-intro-to-basics-1?ex=1). It is a 7 part intro interactive exercise for these topics. Don't worry too much about data types, yes its important, yes its annoying, its something you can learn by doing.






